version: '3.1'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./oauth2.sql:/docker-entrypoint-initdb.d/oauth2.sql
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: 'webshop'
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 60s
      retries: 30
    container_name: webshopdb
    networks:
      - postgres

networks:
  postgres:
    driver: bridge